### ISSUE TITLE
Removal of buildpacks from store using build-id@version format

### ISSUE THREAD

**Issue by sukhil-suresh** [vmware-tanzu/kpack-cli#110]
**Problem:** buildpack removal from a store requires specifying the build image, which is proving to be cumbersome process.

Finding the buildpack image reference requires using the --verbose flag on the `kp clusterstore status <storename>` and is a very long string

Snippet from help text:
```
Usage:
  kp clusterstore remove <store> -b <buildpackage> [-b <buildpackage>...] [flags]

Examples:
kp clusterstore remove my-store -b my-registry.com/my-buildpackage/buildpacks_httpd@sha256:7a09cfeae4763207b9efeacecf914a57e4f5d6c4459226f6133ecaccb5c46271
kp clusterstore remove my-store -b my-registry.com/my-buildpackage/buildpacks_httpd@sha256:7a09cfeae4763207b9efeacecf914a57e4f5d6c4459226f6133ecaccb5c46271 -b my-registry.com/my-buildpackage/buildpacks_nginx@sha256:eacecf914a57e4f5d6c4459226f6133ecaccb5c462717a09cfeae4763207b9ef
```

**Solution:** support buildpack removal from a store using a combination of the buildpack-id and version, which is unique within the store. And, this information is listed as part of the store status command. Example:
```
$ kp csr status default
Status:    Ready

BUILDPACKAGE ID                       VERSION    HOMEPAGE
kpack/git-metadata                    0.0.5
paketo-buildpacks/procfile            2.0.2      https://github.com/paketo-buildpacks/procfile
paketo-buildpacks/procfile            1.4.0      https://github.com/paketo-buildpacks/procfile
paketo-buildpacks/ruby                0.1.0      https://github.com/paketo-buildpacks/ruby
...
```	

Proposed alternative (based on prior art): 
```
kp clusterstore remove my-store -b buildpacks_httpd@0.1.0 -b
kp clusterstore remove my-store -b buildpacks_httpd@1.0.3 -b buildpacks_nginx@1.1.3
```

**Prior art:** kp clusterbuilder/builder create/patch/save now support creation of a builder using flags
Commit: https://github.com/vmware-tanzu/kpack-cli/commit/f5df53c7a182f40abc1adb1752f24292f34dd685
PR: https://github.com/vmware-tanzu/kpack-cli/pull/107

**Discussion:** Do we want to continue support for deletion of buildpack from a store using image reference?

**Comment by mgibson1121** [comment]
This story passes acceptance.
