### ISSUE TITLE
Registry secret type should create a secret using only the registry domain

### ISSUE THREAD

**Issue by tylerphelan** [vmware-tanzu/kpack-cli#133]
for `kp secret create --registry` we document to include a path with the registry:

```
kp secret create my-registry-cred --registry example-registry.io/my-repo --registry-user my-registry-user
```

But this will create an invalid secret because the `dockerconfigjson` secret should use the registry domain only.

We should respond in 2 ways:
1. Change documentation to only pass in the registry:
```
kp secret create my-registry-cred --registry example-registry.io --registry-user my-registry-user
```

2. If users pass in a registry + path (repo) we should create the secret with just the registry:

ie.
```
kp secret create my-registry-cred --registry example-registry.io/my-repo --registry-user my-registry-user
```
should still work

**Comment by mgibson1121** [comment]
This story passes acceptance.
