### ISSUE TITLE
Enhance: kp image list

### ISSUE THREAD

**Issue by aemengo** [vmware-tanzu/kpack-cli#141]
The following captures **2** requests from the [0004-image-filter](https://github.com/pivotal/kpack/blob/master/rfcs/0004-image-filter.md) RFC.

1. ~~Users should be able to filter images on **latest-reason**, even when there are multiple reasons given for an image.~~

      **EDIT:** The previous request has been addressed.

1. Users should not see the **NAMESPACE** column when the namespace flag is used. The namespace flag presently filters results by namespace.

     **When** I invoke `kp image list -n some-ns`
     **And** there is an image present in the specified namespace: `some-ns`
     **Then** I should only see this image in the output
     **Then** I should not see the namespace column as part of the output 

     **Ex.**
     ```
     $ kp image list -n some-ns
 
     NAME              READY     LATEST REASON     LATEST IMAGE                                                                                             

     mg-test-image1    True      CONFIG             gcr.io/cf-build-service-dev-219913/test/mg-test-image@sha1:13D5582884803A7755CEEDCB7478485498C4F1C4
     ...
     ```

**Comment by aemengo** [comment]
I'm not too keen on request 2. I've [brought this up before](https://github.com/vmware-tanzu/kpack-cli/issues/124#issuecomment-730667926) but I wouldn't expect a flag to present a similar but different table.

**Comment by matthewmcnew** [comment]
Wouldn't we only want the Namespace column when they explicitly used the `all-namespaces` flag?
