### ISSUE TITLE
kp should enable users to upgrade the kpack lifecycle image

### ISSUE THREAD

**Issue by tylerphelan** [vmware-tanzu/kpack-cli#142]
RFC: upgradeable lifecycle rfc https://github.com/pivotal/kpack/pull/560 (soon to be merged)

Follows: https://github.com/pivotal/kpack/issues/594

**Problem:**
It is not trivial to update the kpack lifecycle image

**Criteria:**
New `kp` command:

`kp lifecycle upgrade --image <lifecycle-image-tag>` updates the kpack lifecycle image

Where `<lifecycle-image-tag>` is a valid registry tag containing a kpack lifecycle image

**Actions:**
- New kp command `kp lifecycle upgrade`
- New command writes the full image reference to `ConfigMap.lifecycle-image.image` in the `kpack` namespace
- New command reads the image label `io.buildpacks.lifecycle.metadata.apis.platform.supported` and sets the `ConfigMap.lifecycle-image.platformApiVersions` as space-separated values

**Notes:**
- Users must be authenticated with lifecycle image registry
- If image label `io.buildpacks.lifecycle.metadata.apis.platform.supported` is not set, it should fail
- No other validations

**Comment by matthewmcnew** [comment]
Perhaps, we `patch` or `update` instead of `upgrade`?

**Comment by mgibson1121** [comment]
I know this isn't on TBS yet, but one or two thoughts just based on the `kp` interface.  

1.  Help output does not provide examples or a "Usage" section like other `kp` commands do.  Eg. `Usage:
  kp image create <name> --tag <tag> [flags]`

2.  Given the CNB project distributes these as tgz, should that be the format the CLI receives?  Not sure if this poses a lot more work.

**Comment by sukhil-suresh** [comment]
> 1. Help output does not provide examples or a "Usage" section like other `kp` commands do.  Eg. `Usage:   kp image create <name> --tag <tag> [flags]`

This is actually implemented.. possible that you ran it without the subcommand -  `kp lifecycle` and not `kp lifecycle update`?
Attaching screencap below
![Screen Shot 2021-01-28 at 6 29 25 PM](https://user-images.githubusercontent.com/1648613/106211726-30b42380-6197-11eb-8613-cf2607b2d5df.png)

**Comment by sukhil-suresh** [comment]
> 2\. Given the CNB project distributes these as tgz, should that be the format the CLI receives?  Not sure if this poses a lot more work.

This would be a change to the [original requirement](https://github.com/vmware-tanzu/kpack-cli/issues/142#issue-782390292).. but should be easy to add.

It was discussed during the [RFC phase](https://github.com/pivotal/kpack/blob/master/rfcs/0006-upgradeable-lifecycle.md) and can't remember if there was an explicit reason why it was dropped. Will check and update

**Comment by sukhil-suresh** [comment]
> I know this isn't on TBS yet, but one or two thoughts just based on the `kp` interface.

In case you wanted to test the kp functionality standalone (without verifying the kpack side)... you can run `kubectl get cm lifecycle-image -n kpack -o yaml` and check the value of `data.image` after running the `kp lifecycle update` command.
(get the value directly with `k get cm lifecycle-image -n kpack -o json | jq .data.image` if you have jq installed)

**Comment by sukhil-suresh** [comment]
> It was discussed during the [RFC phase](https://github.com/pivotal/kpack/blob/master/rfcs/0006-upgradeable-lifecycle.md) and can't remember if there was an explicit reason why it was dropped. Will check and update

Update: The feature to build a lifecycle image from tarball is **not scoped for the upcoming 0.2 release**. And can be explored post 0.2.

Context: kpack uses a [single lifecycle image](https://github.com/pivotal/kpack/blob/3900cd9e3f42f54c884dc95c4832e4f4fc14d2bd/hack/lifecycle/main.go#L80-L123) for both linux and windows builds. This requires the `kp lifecycle update` command to take in linux and windows lifecycle tarballs and combine them to generate single lifecycle image. The usage is discussed in the [RFC](https://github.com/pivotal/kpack/blob/master/rfcs/0006-upgradeable-lifecycle.md)
```
Additionally, We could add the ability to update by providing the path to the windows and linux lifecycle downloads:

kp lifecycle upgrade --linux "https://github.com/buildpacks/lifecycle/releases/download/v0.9.2/lifecycle-v0.9.2+linux.x86-64.tgz" --windows "https://github.com/buildpacks/lifecycle/releases/download/v0.9.2/lifecycle-v0.9.2+windows.x86-64.tgz"

In this case, kp would assemble the lifecycle image similar to how we do it in our kpack release.
```

**Comment by mgibson1121** [comment]
This story passes acceptance.
