### ISSUE TITLE
kpack lifecycle image is importable

### ISSUE THREAD

**Issue by tylerphelan** [vmware-tanzu/kpack-cli#143]
rfc: https://github.com/pivotal/kpack/pull/560
must follow: https://github.com/pivotal/kpack/issues/594
related issue: https://github.com/vmware-tanzu/kpack-cli/issues/142

Problem:
The kpack lifecycle image should be upgraded as a part of `kp import` for easy dependency management

**Criteria:**
When I run `kp import -f descriptor.yaml` with a descriptor that contains a new lifecycle image, the lifecycle is upgraded

**Actions**
- `descriptor.yaml` contains the lifecycle image with platform api info
- kp import upgrades lifecycle

**Notes**
- This might require a new descriptor `apiVersion`

**Comment by mgibson1121** [comment]
This story passes acceptance.
