### ISSUE TITLE
Include the name of the clusterstack in builder/clusterbuilder status

### ISSUE THREAD

**Issue by mgibson1121** [vmware-tanzu/kpack-cli#157]
Similar to #145 and #146 

**What:** Include the name of stack in the `kp builder status` output

**Why:** We currently just provide the image reference for the Stack 
```
magibson-a01:workspace magibson$ kp clusterbuilder status default
Status:       Ready
Image:        gopivotal-build-service-private.jfrog.io/deletable/staging/default@sha256:c1a346d6da44569600161b91ea126c0829be1774dc55b5c670379413c826da41
Stack:        io.buildpacks.stacks.bionic
Run Image:    gopivotal-build-service-private.jfrog.io/deletable/staging/run@sha256:70accedc26b4d9230ce6ae4b1e55a0588bb14447e074d8fc65bd3ced4211630b
```
It would be helpful when debugging Not Ready builders to be able to quickly check the status of these other resources by referencing them by name rather than trying to figure out how to match the image reference to the resource name (or using kubectl)

**Comment by dumez-k** [comment]
Spoke to @matthewmcnew @tomkennedy513 about this issue. Instead of just providing the stack name, a proposal we came up with was to provide the whole stack and store ref.

This makes it clearer what the configured inputs are from the result output.

Any thoughts @mgibson1121 ?

```
Stack Ref:
  Name: base
  Kind: clusterstack
Store Ref:
  Name: default
  Kind: clusterstore
Status:       Ready
Image:        gopivotal-build-service-private.jfrog.io/shipyard/default@sha256:81dc3d76256583803308bc9b00abc86267daa07b18e469b9a4c95690fbcd33dd
Stack:        io.buildpacks.stacks.bionic
Run Image:    gopivotal-build-service-private.jfrog.io/shipyard/run@sha256:367a43536f60c21190cea5c06d040d01d29f4102840d6b3e1dcd72ed2eb71721
```

**Comment by mgibson1121** [comment]
Looks great!  Closing.
