### ISSUE TITLE
`go get ...` isn't working after move from pivotal/kpack to vmware-tanzu/kpack-cli

### ISSUE THREAD

**Issue by hiremaga** [vmware-tanzu/kpack-cli#158]
This is the first time I tried to install `kp` on my Mac. First I looked for a brew package. Then, I tried to install the `kp` cli using `go get github.com/vmware-tanzu/kpack-cli` but ran into an error, see below. 

```
% go get github.com/vmware-tanzu/kpack-cli
go: downloading github.com/vmware-tanzu/kpack-cli v0.2.0
go: github.com/vmware-tanzu/kpack-cli upgrade => v0.2.0
go get: github.com/vmware-tanzu/kpack-cli@v0.2.0: parsing go.mod:
	module declares its path as: github.com/pivotal/build-service-cli
	        but was required as: github.com/vmware-tanzu/kpack-cli

% go version
go version go1.15.8 darwin/amd64
```
This looks like it might be a consequence of the repo being moved.

Per the README, I was able to install `kp` from source by explicitly cloning the repo and running `go install ./cmd/kp`. I also didn't try the latest release binary, but I expect that might've worked as well.

**Comment by matthewmcnew** [comment]
This is now fixed with the module defining the correct module name.
