### ISSUE TITLE
Allow users to configure `kp-config` with `kp`

### ISSUE THREAD

**Issue by matthewmcnew** [vmware-tanzu/kpack-cli#160]
Currently, commands that involve adding buildpack images and stack images via `kp` (`clusterstore add`, `clusterstack update`, `import`) require a config map known as `kp-config` to configured on cluster with a configured registry (canonical-registry). Currently, this configmap needs to be created and updated by hand. 

It would be useful to allow kp to configure and update this value. This could be accomplished with:

`kp config set canonical-registry <my-registry>`

**Comment by matthewmcnew** [comment]
Unresolved questions:

- How do we handle auth for the canonical-registry if it is a private? 
- Is `config set` the right terminology?

**Comment by tomkennedy513** [comment]
should we do `kp config set canonical-repository` since that is the term we typically use

**Comment by matthewmcnew** [comment]
Yes, `canonical-repository` is the right term..

**Comment by tylerphelan** [comment]
plan:
- `kp config set canonical-repository <repo>`
  - also sets canonical-repository.serviceaccount to `default` if uneset
  - use `default` for this service account in TBS
- add issue for setting service account for different resources (`--serviceaccount` flag)
- Add issue ability to modify kp config service account

**Comment by tylerphelan** [comment]
**interface discussion:**
How to design `kp config set`
- `Kp config set canonical-repository` (kubectl style-?)
  - `Kp config add list-thing thing`
  - `Kp config rotate kpack-key`
  - `kp config rotate canonical-repository`
  - `kp config set canonical-service-account.namespace my-namespace` 
  - `kp config set canonical-service-account.service-account my-sa`
- Kp config set-canonical-repository (kubectl style)
  - similar to `Kubectl config set-context <args>`
  - `Kp config get-canonical-repository`
  - `Kp config add-list-thing`
  - `Kp config remove-list-thing`
  - `Kp config rotate-kpack-key`
  - `Kp config set-canonical-service-account --namespace my-namespace --service-account my-serviceaccount`
- Kp config canonical-repository (pack style)
  - similar to [pack config experimental false rfc](https://github.com/buildpacks/rfcs/pull/93)
  - `kp config canonical-repository`
  - `kp config list-thing add blah`
  - `Kp config list-thing remove blah`
  - `Kp config kpack-key rotate`
  - `Kp config canonical-service-account --namespace my-namespace --service-account my-serviceaccount`
- generic kubectl style `kp config set clusters.my-cluster.server https://1.2.3.4`
- Necessary values to set: 
  - Canonical-repository
  - canonical-repository-service-account

**Comment by tylerphelan** [comment]
this won't change the `canonical-registry-secret` used in the build service namespace :(

**Comment by tylerphelan** [comment]
THREE

**Comment by tomkennedy513** [comment]
team decided to go with option 3

**Comment by tomkennedy513** [comment]
after discussing we will default to the "default" service account in the kpack namespace when a user sets the canonical repository initially
