### ISSUE TITLE
Official kp docker image 

### ISSUE THREAD

**Issue by matthewmcnew** [vmware-tanzu/kpack-cli#180]
It would be useful to publish an official `kp` docker image to use in ci/cd contexts. This would be similar to the [carvel docker image](https://github.com/vmware-tanzu/carvel-docker-image).

**Comment by mgibson1121** [comment]
During a conversation on 7/9 we aligned that it would also be helpful to ship Carvel tools and kubectl in this image.

**Comment by tylerphelan** [comment]
https://hub.docker.com/r/kpack/kp
