### ISSUE TITLE
Add Image Name to `kp build list`

### ISSUE THREAD

**Issue by matthewmcnew** [vmware-tanzu/kpack-cli#206]
**Why**
`kp build list` currently will displays builds for multiple images. However, the tabular display does not show the image that corresponds to the build. This makes it difficult to "work backwards" and find the corresponding image for a build. 

**What**
A new column known as Image Resource in `kp build list` should display the Image name.

**Comment by alexbarbato** [comment]
Would love this!

For an additional use case where this becomes particularly important is in the case of `kp build logs IMAGE_NAME`
