### ISSUE TITLE
Clarify CLI output and help text to refer to the image resource

### ISSUE THREAD

**Issue by sampeinado** [vmware-tanzu/kpack-cli#207]
**Why**
Interviews with kpack users (n=4), particularly those who teach kpack to others, have expressed frustration at the overloaded use of the name 'image' being used to describe the core custom resource produced by kpack. Today, "image" means a _container_ image in industry standard terminology. In order to alert new users that an image in kpack is a new concept (_not_ a container image), we should differentiate or clarify the name of the image resource in kpack in order to help new users understand the purpose of kpack and get going quickly. 

Looking into the current state of the CLI around this issue revealed that we are currently inconsistent in how we reference or explain the kpack image. 

**What**
1. Find and replace all references to the term "image" with "image resource" in CLI help text, CLI command output and documentation (docs issue [here](https://github.com/pivotal/kpack/issues/850)).  This includes ALL kp commands, not just the image command.
2. Add a new secondary alias, `image-resource`,  to the `kp image` command.

Example: 
![CURRENT CLI](https://user-images.githubusercontent.com/35495560/136053113-88a7132f-0d91-4d37-bac0-60a6beec08ec.png)
![PROPOSED CLI](https://user-images.githubusercontent.com/35495560/136053121-e58bd89f-159f-4c9d-af66-accc63000065.png)

**Comment by tomkennedy513** [comment]
Closing stale issue, reopen to continue this conversation
