### ISSUE TITLE
Add Service Bindings Interface to kpack CLI

### ISSUE THREAD

**Issue by mgibson1121** [vmware-tanzu/kpack-cli#235]
Currently, kpack CLI does not support configuring service bindings on the kpack Image.  We provide robust documents for this in the kpack repo (https://github.com/pivotal/kpack/blob/main/docs/servicebindings.md), but we've received complaints from users that it seems hidden.  Given many users will have this use case (eg. building a Maven app with a settings.xml binding), we should consider its inclusion in the kpack CLI.

**Comment by chenbh** [comment]
Current thought is to add a repeatable `--service-binding <KIND>/<VERSION>=<NAME>` to the `kp image create/save/patch` commands

**Comment by chenbh** [comment]
Found references to `ImageBuild.CNBBindings` in the code, judging by https://github.com/pivotal/kpack/blob/main/docs/legacy-cnb-servicebindings.md, it's deprecated so we don't need to support it in the CLI

**Comment by tylerphelan** [comment]
Let's also add a `kp secret create --service-binding` of some kind

**Comment by tylerphelan** [comment]
> Current thought is to add a repeatable `--service-binding <KIND>/<API VERSION>:<NAME>` to the `kp image create/save/patch` commands.
> 
> By k8s standards, `<KIND>` can only contain letters and periods, and can only be alphanumeric, which ensures we can split by ':'.
> 
> The `--service-binding` flag is similar to the `--env` flag and the only 3 commands I can find that takes `--env` is the `image create/save/patch` subcommands.

looks good. Let's make `KIND/APIVERSION` optional and if unset it defaults to `Secret` with no api version (still valid)

**Comment by chenbh** [comment]
> Let's also add a `kp secret create --service-binding` of some kind

How about:

`--service-binding-type <TYPE>`: Recommended, sets`.type: servicebinding.io/<TYPE>` and `.stringData.type: <TYPE>`
`--service-binding-provider <PROVIDER>`: Optional, sets `.stringData.provider: <PROVIDER>`
`--service-binding-value <KEY>=<VALUE>`: Optional, sets `.stringData.<KEY>: <VALUE>`
`--service-binding-data <KEY>=<FILE PATH>`: Optional, sets `.stringData.<KEY>` with the contents of `<FILE PATH>`

One thing I'm not fully sold on is if there should be a flag to set more sensitive values with a password prompt. Something like `--service-binding-secret key1,key2,key3....` and then there would be a hidden input prompt for each of those keys.

**Comment by matthewmcnew** [comment]
Are we providing that much value over what you can (and probably should) do with kubectl when creating secrets?

**Comment by matthewmcnew** [comment]
> Current thought is to add a repeatable --service-binding <KIND>/<API VERSION>:<NAME> to the kp image create/save/patch commands.

Is there any prior art on other clis here?

**Comment by chenbh** [comment]
> > Current thought is to add a repeatable --service-binding /: to the kp image create/save/patch commands.
> 
> Is there any prior art on other clis here?

This is how it works for the `--env flag`, you can have `--env foo=bar --env bar=baz --env ...`.

I would say this is a fairly consistent pattern from `tanzu apps workload create --build-env ...` to `helm install --set ...`, and `kapp deploy --labels ...`

**Comment by matthewmcnew** [comment]
It looks like [kn cli](https://knative.dev/docs/client/install-kn/) takes the same approach. 
"This argument takes format kind:apiVersion:name for named resources"

**Comment by chenbh** [comment]
Good catch, forgot that versions can include forward slashes (`apps/v1`, `authentication.k8s.io/v1`)
