### ISSUE TITLE
Use PATCH instead of PUT when modifying existing resources 

### ISSUE THREAD

**Issue by matthewmcnew** [vmware-tanzu/kpack-cli#236]
## Background
When users utilize the https://github.com/vmware-tanzu/kpack-cli/releases/tag/v0.4.2 kp release on resources with v1alpha2 fields (such as additionalTags) the `kp` cli will execute a PUT in the v1alpha1 api format leading to the existing v1alpha2 fields being overwritten. This will be a problem with new apis if the kp cli migrates to use v1alpha2 by default. 

## What
The `kp` cli should not use HTTP PUT but, instead use a PATCH to only modify the relevant fields. 

There is now a new issue that isn't resolved by just PATCHING

**Comment by tylerphelan** [comment]
started: https://github.com/vmware-tanzu/kpack-cli/tree/use-patch-everywhere

**Comment by tylerphelan** [comment]
> There is now a new issue that isn't resolved by just PATCHING
Fixed https://github.com/pivotal/kpack/pull/934
