### ISSUE TITLE
Remove BOM support

### ISSUE THREAD

**Issue by tylerphelan** [vmware-tanzu/kpack-cli#239]
Background:
The `kp` cli has a feature to show the [bom](https://buildpacks.io/docs/buildpack-author-guide/create-buildpack/adding-bill-of-materials/) of any given oci image by running `kp build status --bom`

Motivation:
This feature has confused users and is now considered out of scope for the `kp` cli. This type of information should not be part of the kpack api and instead is only accessible via the OCI image itself. The `pack` cli can be used to get this information.

Deliverable:
When: I run `kp build status --bom`
Then: I get a `this flag does not exist` or similar error.

Notes:
- Essentially we are removing the `--bom` flag

**Comment by pviraj59** [comment]
@tylerphelan - can we add some context here when you get a chance please
