### ISSUE TITLE
`kp image create` prevents default cache volume from being added.  

### ISSUE THREAD

**Issue by matthewmcnew** [vmware-tanzu/kpack-cli#250]
### Expected Behavior
The kp image create/save command:
`kp image create <image-name> --tag <some-tag> --git <some-git-url>`

Should not set a cache volume size allowing the kpack-webhook to default it when the resulting cluster has a default storage class:

```
spec:
  cache:
    volume:
      size: 2G
```
### Actual Behavior
However, the actual created image is not getting the default volume created. 
```
spec:
  cache:
    volume: {}
```

**Comment by tomkennedy513** [comment]
pr https://github.com/vmware-tanzu/kpack-cli/pull/259
