### ISSUE TITLE
Publish kp for arm architectures

### ISSUE THREAD

**Issue by tylerphelan** [vmware-tanzu/kpack-cli#252]

**Comment by ThomasVitale** [comment]
What is needed to make this possible? I would be happy to help!

**Comment by tomkennedy513** [comment]
Hi @ThomasVitale this was actually completed for darwin arm (m1 macs) as of kp 0.6.1, we must have forgotten to close this issue.

**Comment by ThomasVitale** [comment]
@tomkennedy513 That's fantastic! Thank you very much!
