### ISSUE TITLE
Summary of changes & Confirmation for the `kp import` command

### ISSUE THREAD

**Issue by sukhil-suresh** [vmware-tanzu/kpack-cli#28]
[kp import](https://github.com/pivotal/build-service-cli/issues/26) is a powerful command capable of making a broad set of resource changes (based on what is defined in the DependencyDescriptor yaml file). Considering this, it would be helpful to provide the user
- a summary visualization of the changes that will be applied
- and request confirmation before proceeding to apply the changes

This is probably more helpful/relevant in the upgrade scenario.

How to display the summary of changes is to be decided - do we want a tabular form or a delta on the yaml? or both forms supported by different flags are all up for discussion...

Prior art includes [kapp deploy|delete](https://get-kapp.io/) and the Concourse fly CLI

**Comment by tylerphelan** [comment]
We are adding a `--show-changes` flag to make this behavior opt-in
