### ISSUE TITLE
Add `--dry-run` to kp commands so that they produce yaml that can be `kubectl` applied

### ISSUE THREAD

**Issue by djoyahoy** [vmware-tanzu/kpack-cli#37]
`kp` create and patch commands should be able to produce yaml output with a `--dry-run` flag.

Context: this helps to enable a Gitops workflow so that the yaml can be reused in the git repo that triggers the pipeline

**Comment by sukhil-suresh** [comment]
`--dry-run` and `--output` flags are supported for the kp subcommands:
- builder create/patch/save
- clusterbuilder create/patch/save
- clusterstack create/update/save
- clusterstore created/add/save
- image create/patch/save
- import
- secrete create

`--dry-run` is helpful for client side validation of a given command and will not result in the creation/update/deletion of kpack custom K8s resources. The output of the command will be printed with a `(dry run)` suffixed. Eg:
```
$ kp builder create test-builder --tag sukhilsuresh/test-image --order order.yaml --store test-store --stack test-stack --dry-run
Builder "test-builder" created (dry run)
```

`--output` will allow you to view the resource (output in yaml or json format) sent to the server. This can be used with the --dry-run flag to get the resource output wihout actually creating the resource. Example:

```
$ DOCKER_PASSWORD=password kp secret create my-dockerhub-creds --dockerhub sukhilsuresh --dry-run --output yaml
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzdWtoaWxzdXJlc2giLCJwYXNzd29yZCI6InBhc3N3b3JkIn19fQ==
kind: Secret
...
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
imagePullSecrets:
- name: my-dockerhub-creds
kind: ServiceAccount
...
secrets:
- name: default-token-4w24f
- name: my-dockerhub-creds
```


You should be able to apply `kubectl apply` any of the resource output. Applies for all commands that support the `--output`flag 
```
$ kp image create timg6 -t sukhilsuresh/timg6 --local-path /Users/ssuresh/workspace/spring-petclinic --output yaml --dry-run | k apply -f -
Uploading to 'index.docker.io/sukhilsuresh/timg6-source'... (dry run)
image.kpack.io/timg6 created
```

You could also pipe the output for a resource along with it's creation
```
$ kp image create timg6 -t sukhilsuresh/timg6 --local-path /Users/ssuresh/workspace/spring-petclinic --output json > timg6.json
Uploading to 'index.docker.io/sukhilsuresh/timg6-source'...
	Uploading 'index.docker.io/sukhilsuresh/timg6-source@sha256:f535e85e5946bfde7b2951a5dab43b1bf9a35f7e25dc0499937169abf6cfaa15'

$ cat timg6.json
{
    "kind": "Image",
    "apiVersion": "kpack.io/v1alpha1",
    ...

}
```

**Comment by mgibson1121** [comment]
Just took a look and this works according to the conversation discussed here.  @sukhil-suresh One thing to consider is providing a bit more context in the help output for the `--dry-run` flag.  It currently reads ` only print the object that would be sent, without sending it`.  I can see some users being confused running the command without the dry run flag and not seeing output.  Maybe something like `print the object that would be sent without sending it, use --output flag to specify format`

**Comment by sukhil-suresh** [comment]
pulled the story back into done for now, since it waiting on [this PR to merge](https://github.com/vmware-tanzu/kpack-cli/pull/114)

The help text now reads like below. wondering if it is ok? or do we need more change
```
Flags:
...
      --dry-run                        perform validation with no side-effects; no objects are sent to server
      --dry-run-with-image-upload      similar to --dry-run, but image uploads are allowed
...
```

**Comment by sukhil-suresh** [comment]
@mgibson1121 marked story for acceptance

**Comment by mgibson1121** [comment]
@sukhil-suresh Not seeing the help text you link in your PR show up using the latest `kp` binary I can find (Darwin 34).

**Comment by mgibson1121** [comment]
This story passes acceptance
