### ISSUE TITLE
`kp build list` prints a very wide table 

### ISSUE THREAD

**Issue by mgibson1121** [vmware-tanzu/kpack-cli#44]
Leads to problems rendering well in a smaller terminal window. we could have a verbose flag that prints more or do some kind of "detect length" before printing output

**Comment by tylerphelan** [comment]
Criteria: Drop `STARTED` and `FINISHED` columns for MVP

**Comment by mgibson1121** [comment]
I mistakenly thought that the `STARTED` and `FINISHED` times were available in the build status.  If we remove it from the table, we should consider surfacing there.
