### ISSUE TITLE
Add Lifecycle metadata to `kp build status` behind `--bom` flag

### ISSUE THREAD

**Issue by mgibson1121** [vmware-tanzu/kpack-cli#48]
**Problem**

While `kp build status` is certainly helpful, we currently do not provide all the Bill of Materials metadata the lifecycle can make available to the kpack CLI from upstream.  Doing so would be particularly helpful to provide information about the dependencies shipped by the buildpacks used to execute the build.  This information would be helpful to users when performing audit functions and determining which image to promote to a new environment.  

**Outcomes**

**Given** I have created the image config `node-test-app` 
**When** I run `kp build status node node-test-app --bom`
**Then** I see lifecycle BOM output

```
{"remote":null,"local":[{"name":"node","version":"10.22.0","metadata":{"licenses":[],"name":"Node Engine","sha256":"43616969dd39d52c9d3c0a4ed5e66600133356877ab8344a916638e7f5794490","stacks":["io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"],"uri":"https://buildpacks.cloudfoundry.org/dependencies/node/node_10.22.0_linux_x64_cflinuxfs3_43616969.tgz"},"buildpack":{"id":"paketo-buildpacks/node-engine","version":"0.0.260"}},{"name":"node_modules","version":"","metadata":null,"buildpack":{"id":"paketo-buildpacks/npm","version":"0.1.79"}}]}
```

**Notes** 

* This story is intended to surface the bom metadata in the `kp` CLI and does not preclude further structuring to make it more legible to users
* Usage of common pretty print tools like `jq` improve the legibility of the metadata dramatically, could it be a quick win to encourage people to download it in our docs or in the CLI help output (or both?)

**Comment by mgibson1121** [comment]
Reviving the conversation on this story given there was a request for it.  I feel we can talk this through in the Github threads rather than submitting a larger RFC.  I like elements of Sam's proposal and will address @matthewmcnew's comments.

1) Agreed we should remove the `{"remote": ... ,"local": ... }` output from the BOM produced by `kp`

2) Usage of `--bom` flag rather than `--verbose`.  Although we use `--verbose` in other commands with configurable levels of depth in `kp`, I think it makes sense to use `--bom` here because it is communicated explicitly as a benefit of using CNBs,

3) I like Sam's proposal of printing the BOM output at the bottom of the status rather than trying to mix metadata provided by the BOM with the structured output provided by the build diff RFC

4) In the event of a build that is not in a successful state, the complicating factor AFAICT is that we would have different metadata to display in the BOM output depending on how far in the lifecycle the build progressed.  It would help if an engineer could confirm my previous comment by looking at the code because I am going off of memory of past usage and not sure how to reproduce a scenario in which I could confirm this myself.  In any event, I think we should ideally display all the metadata available depending on how far the build progressed in the lifecycle.

5) How should we structure the output?  This to me is the most delicate question.  We could pursue custom visualization of the output like we did in the build diff RFC or just dump the non-pretty JSON.  Personally, I would like to take the quick win and make the output available in the `kp` CLI.  There is precedent for this approach in the `kp CLI`.  The `verbose` flag on the `clusterstack status` command returns an unstructured list of mixins.  If there is a way to return structured JSON as a feature of the CLI similar to what `jq` does, imo that would be a great initial stab at this experience.

**Comment by mgibson1121** [comment]
My above proposal was edited based on feedback from the 11/6 working group.

**Comment by matthewmcnew** [comment]
> In the event of a build that is not in a successful state, if the user runs kp build status --bom, the command would succeed the output would be blank. This decision is based on the fact that we cannot surface a BOM unless the lifecycle finishes the export phase successfully.

We should probably provide an explicit error here.

**Comment by matthewmcnew** [comment]
It is worth noting that we don't save the bom on the build status so, this would require the `kp` cli to query the registry to get the bom output. This would require the user to have local registry credentials on their machine to access the registry. This is (probably?) alright but, it will be first command that queries the registry for information.

**Comment by mgibson1121** [comment]
1) Agreed we should remove the {"remote": ... ,"local": ... } output from the BOM produced by kp

2) Usage of --bom flag rather than --verbose. Although we use --verbose in other commands with configurable levels of depth in kp, I think it makes sense to use --bom here because it is communicated explicitly as a benefit of using CNBs.

3) In the WG meeting on 11/6 we aligned behind the notion that kp build status and kp build status --bom should be two separate commands. Reason being that we will output the BOM as JSON and expect that many users will likely process the output using a tool like jq. If we were to include the BOM as a section in the output of kp build status, this would pose problems for parsing the JSON because we take a design opinion of the metadata currently returned by this command.

4) In the event of a build that is not in a successful state, if the user runs kp build status --bom, we should print an error message 

5) As @matthewmcnew mentions above, the `kp` CLI will need to query the registry.  If the user has not provided `kp` with their registry credentials (eg. via using the source upload), we should return an error message specifying that the command could not access the registry.

**Comment by tylerphelan** [comment]
Does this look right?:

```
kp build status image --bom | jq .
{
  "bom": [
    {
      "name": "node",
      "version": "10.22.1",
      "metadata": {
        "licenses": [],
        "name": "Node Engine",
        "sha256": "d84ec1b77780923f2d0d30f9155dfcba411c67ae53548684a140b2ec982fdeba",
        "stacks": [
          "io.buildpacks.stacks.bionic",
          "org.cloudfoundry.stacks.cflinuxfs3"
        ],
        "uri": "file:///dependencies/d84ec1b77780923f2d0d30f9155dfcba411c67ae53548684a140b2ec982fdeba",
        "version": "10.22.1"
      },
      "buildpack": {
        "id": "tanzu-buildpacks/node-engine",
        "version": "0.1.1"
      }
    },
    {
      "name": "node_modules",
      "metadata": {
        "launch": true
      },
      "buildpack": {
        "id": "tanzu-buildpacks/npm-install",
        "version": "0.1.1"
      }
    }
  ],
  "buildpacks": [
    {
      "id": "tanzu-buildpacks/node-engine",
      "version": "0.1.1"
    },
    {
      "id": "tanzu-buildpacks/npm-install",
      "version": "0.1.1"
    },
    {
      "id": "tanzu-buildpacks/npm-start",
      "version": "0.0.2"
    }
  ],
  "launcher": {
    "version": "0.9.2",
    "source": {
      "git": {
        "repository": "github.com/buildpacks/lifecycle",
        "commit": "ee48447"
      }
    }
  },
  "processes": [
    {
      "type": "web",
      "command": "node server.js",
      "args": null,
      "direct": false,
      "buildpackID": "tanzu-buildpacks/npm-start"
    }
  ]
}
```
