### ISSUE TITLE
Diff btwn Builds / Why the Build Happened

### ISSUE THREAD

**Issue by sampeinado** [vmware-tanzu/kpack-cli#54]
Track of work for Design addressing thre issues:

48. BoM [issue](https://github.com/pivotal/kpack-cli/issues/48)

155. Diff [issue](https://github.com/pivotal/build-service/issues/155)

58. Why [issue](https://github.com/pivotal/kpack-cli/issues/58)

Notes [doc](https://docs.google.com/document/d/1on6izjC5r8fQLMPS8Q7UglTxLOErzj10NHBuzKPEVzs/edit#)

- [X] Prepare design plan (and write "user stories" for the scenarios) [PE] 
- [x] Compare the current state of pack and kpack [PE] 
- [x] Lay them out in a board [PD] and look for the relationships among them [PD]
- [x] Get input from McNew on the scenarios [PD]
- [x] Draft a solution idea for why the build kicked off and whats in the build [SE]
- [x] Gather examples of diffs in other services [SE]
- [x] Draft a solution idea for diff [SE]
- [x] Get feedback from the team on the feasibility of the ideas [SD]
- [x] Get feedback from Madhura, X, Y, Z on whether these solutions satisfy their needs [SD]

**Comment by mgibson1121** [comment]
Closing this issue and it's corresponding build-service ticket as the RFC has been delivered and approved.
