### ISSUE TITLE
kp import is hanging

### ISSUE THREAD

**Issue by tylerphelan** [vmware-tanzu/kpack-cli#59]
Users have reported kp import hanging or taking a long time.

1. 
User logs installing on dockerhub:

```
kp import -f descriptor.yaml
Importing Cluster Store 'default'...
Uploading to 'my-repo'...
```

2.
Quote from user using harbor:

"Quick update: the kp import command line seems to hang"

3.
User quote:

"Import is underway but is pretty slow, I’m capped at around 5.0 Mbps for the download speed."

Actions:

It's hard to validate this issue is more than just an internet connection bottleneck. 

However, a potential improvement would be importing in parallel.

**Comment by matthewmcnew** [comment]
Some docker-esque upload bars would be great.

**Comment by mgibson1121** [comment]
Moving back to TBS Issues
