### ISSUE TITLE
Consistency in wording between kp build status and kp image status

### ISSUE THREAD

**Issue by sampeinado** [vmware-tanzu/kpack-cli#71]
`kp build status` has a line in its output for "Reasons" whereas `kp image status` has a line for "Reason," both of which are associated with the same key value pair (to explain the reason a build kicked off). 

Let's change one of them so that they are both consistent. 

I propose changing `kp build status` to say Reason instead of Reasons because even when there are multiple reasons, each will show up on a new line, making the user read each reason separately. Also Reason feels like it makes sense for singular and plural values whereas Reasons feels like it only makes sense for plural values. 

Current state for kp cli version 0.0.1-build.3 3e7d6d3:

<img width="781" alt="Screen Shot 2020-09-15 at 1 35 39 PM" src="https://user-images.githubusercontent.com/35495560/93245324-2b5ebb00-f759-11ea-8687-9e2c7fac1084.png">
<img width="668" alt="Screen Shot 2020-09-15 at 1 35 47 PM" src="https://user-images.githubusercontent.com/35495560/93245333-2f8ad880-f759-11ea-8cc7-a7b986b434f6.png">

**Comment by tylerphelan** [comment]
I went with `Build Reason` for both image and build status. This is because _sometimes_ with `kp build status` we report `Build Reason` and `Status Reason` to indicate an error with the build for this issue: https://github.com/vmware-tanzu/kpack-cli/issues/42

Using `Build Reason` and `Status Reason` distinguishes the two.

Ex.

```
$ kp build status my-image
Image:             repo.com/image-3:tag
Status:            BUILDING
Build Reason:      TRIGGER
Status Reason:     some-reason
Status Message:    some-message

Pod Name:    some-pod

Builder:      some-repo.com/my-builder
Run Image:    some-repo.com/run-image

Source:    Local Source

BUILDPACK ID    BUILDPACK VERSION
bp-id-1         bp-version-1
bp-id-2         bp-version-2
```

```
$ kp image status my-image
Status:         Not Ready
Message:        --
LatestImage:    test-registry.io/test-image-1@sha256:abcdef123

Last Successful Build
Id:              1
Build Reason:    CONFIG

Last Failed Build
Id:              2
Build Reason:    COMMIT,BUILDPACK
```
