### ISSUE TITLE
clusterstack update does not update k8s resource

### ISSUE THREAD

**Issue by djoyahoy** [vmware-tanzu/kpack-cli#82]
clusterstack update will fail to update the k8s resource if either the run or build images already exist in the desired registry. The CLI outputs stack unchanged instead of updating the run or build image on the stack resource.

**Comment by tylerphelan** [comment]
repeat? https://github.com/vmware-tanzu/kpack-cli/issues/33

**Comment by warroyo** [comment]
@tylerphelan I think so. basically if either image exists already in the registry it skips the update.which I think is what you reported in that issue.

**Comment by djoyahoy** [comment]
@warroyo @tylerphelan I'm going to close this in favor of #33
